=== cypressious/cypressious.github.io/src/data/projects-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "title",
      "subtitle",
      "tags",
      "links"
    ],
    "additionalProperties": true,
    "properties": {
      "title": {
        "type": "string"
      },
      "subtitle": {
        "type": "string"
      },
      "tags": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "links": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "icon",
            "title",
            "href"
          ],
          "additionalProperties": true,
          "properties": {
            "icon": {
              "type": "string"
            },
            "iconCategory": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "href": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== cypressious/cypressious.github.io/src/data/projects.json
[
  {
    "title": "KIT Mensa App",
    "subtitle": "Android app for the KIT canteen plan",
    "tags": [
      "Android",
      "Java",
      "Kotlin"
    ],
    "links": [
      {
        "icon": "google-play",
        "title": "Google Play",
        "href": "https://play.google.com/store/apps/details?id=com.cypressworks.mensaplan"
      },
      {
        "icon": "github",
        "title": "Github",
        "href": "https://github.com/cypressious/KitMensaAndroid"
      }
    ]
  },
  {
    "title": "Kotlin WebExtensions API Declarations",
    "subtitle": "A generator for Kotlin JS declarations for the Firefox WebExtensions API",
    "tags": [
      "Kotlin",
      "JavaScript",
      "Browser Extensions"
    ],
    "links": [
      {
        "icon": "github",
        "title": "Github",
        "href": "https://github.com/cypressious/kotlin-webextensions-declarations"
      }
    ]
  },
  {
    "title": "Feedly Open Unread",
    "subtitle": "Firefox & Chrome extension for opening all unread items on feedly.com in new tabs",
    "tags": [
      "Javascript",
      "Firefox"
    ],
    "links": [
      {
        "icon": "firefox-browser",
        "title": "Firefox Add-ons",
        "href": "https://addons.mozilla.org/de/firefox/addon/feedly-open-all-unread/"
      },
      {
        "icon": "github",
        "title": "Github",
        "href": "https://github.com/cypressious/ff-feedly-open-unread"
      }
    ]
  },
  {
    "title": "Container Outgoing Links",
    "subtitle": "Firefox extension for opening outgoing links from a container in the default container",
    "tags": [
      "Javascript",
      "Firefox"
    ],
    "links": [
      {
        "icon": "firefox-browser",
        "title": "Firefox Add-ons",
        "href": "https://addons.mozilla.org/de/firefox/addon/container-outgoing-links/"
      },
      {
        "icon": "github",
        "title": "Github",
        "href": "https://github.com/cypressious/ff-container-outgoing-links"
      }
    ]
  }
]
